export type Certificate = {
    id: number;
    title: string;
    institution: string;
    imageUrl: string;
    date: string;
    category: string;
  };
  
  export const certificates: Certificate[] = [
    {
        id: 1,
        title: 'Análise e Desenvolvimento de Sistemas',
        institution: 'UNIP – Universidade Paulista',
        imageUrl: '/certificates/courses/analise-desenvolvimento-de-sistemas.webp',
        date: '01/06/2019',
        category: 'Graduação',
      },
      {
        id: 12,
        title: 'GitLab CI - Para Pipelines CI/CD & DevOps',
        institution: 'Claudio Antonio da Silva',
        imageUrl: '/certificates/courses/gitlab-ci-pipelines-cicd-devops.webp',
        date: '14/06/2023',
        category: 'Horas',
      },
      {
        id: 13,
        title: 'TypeScript do básico ao avançado (c/ React, Express)',
        institution: 'Matheus Battisti',
        imageUrl: '/certificates/courses/typescript-do-basico-ao-avancado.webp',
        date: '07/06/2023',
        category: 'Horas',
      },
      {
        id: 14,
        title: 'Docker: Ferramenta essencial para Desenvolvedores',
        institution: 'Leonardo Moura Leitao / Cod3r',
        imageUrl: '/certificates/courses/docker-ferramenta-essencial-para-desenvolvedores.webp',
        date: '07/05/2023',
        category: 'Horas',
      },
      {
        id: 2,
        title: 'SOLID - Os 5 Princípios Para as Boas Práticas da POO',
        institution: 'Jorge Sant Ana',
        imageUrl: '/certificates/courses/solid-os-5-principios-para-as-boas-praticas-da-poo.webp',
        date: '25/04/2023',
        category: 'Horas',
      },
      {
        id: 3,
        title: 'Vue JS 3: Desenvolvimento Web Moderno com Vuex & Vue Router',
        institution: 'Ivan Lourenço Gomes',
        imageUrl: '/certificates/courses/css-avançado.webp',
        date: '14/04/2023',
        category: 'Horas',
      },
      {
        id: 4,
        title: 'CSS Avançado - Sass, CSS Grid Layout e CSS Modules',
        institution: 'Brunão Sousa',
        imageUrl: '/certificates/courses/vue-js-3.webp',
        date: '14/04/2023',
        category: 'Horas',
      },
      {
        id: 5,
        title: 'Scrum para Desenvolvedores de Software',
        institution: 'Bruno Coutinho',
        imageUrl: '/certificates/courses/scrum-para-desenvolvedores-de-software.webp',
        date: '05/01/2023',
        category: 'Horas',
      },
      {
        id: 6,
        title: 'Git e Github Essencial para o Desenvolvedor',
        institution: 'Geek University',
        imageUrl: '/certificates/courses/git-e-github-essencial.webp',
        date: '02/01/2023',
        category: 'Horas',
      },
      {
        id: 7,
        title: 'Trilha Especializar',
        institution: 'Rocketseat',
        imageUrl: '/certificates/courses/discover-especializar-certificate.webp',
        date: '14/10/2022',
        category: 'Horas',
      },
      {
        id: 8,
        title: 'Trilha Fundamentar',
        institution: 'Rocketseat',
        imageUrl: '/certificates/courses/discover-fundamentar-certificate.webp',
        date: '02/09/2022',
        category: 'Horas',
      },
      {
        id: 9,
        title: 'Trilha Conectar',
        institution: 'Rocketseat',
        imageUrl: '/certificates/courses/discover-conectar-certificate.webp',
        date: '09/08/2022',
        category: 'Horas',
      },
      {
        id: 10,
        title: 'PHP 7 Completo',
        institution: 'Hode',
        imageUrl: '/certificates/courses/php7-hcode.webp',
        date: 'Jun 09, 2022',
        category: 'Horas',
      },
      {
        id: 11,
        title: 'Git e GitHub do básico ao avançado',
        institution: 'Matheus Battisti',
        imageUrl: '/certificates/courses/git-github-avancado.webp',
        date: 'Mai 24, 2022',
        category: 'Horas',
      },
  ];
  
  const posts = [
    {
        id: 1,
        title: 'Análise e Desenvolvimento de Sistemas',
        institution: 'UNIP – Universidade Paulista',
        imageUrl: '/certificates/courses/analise-desenvolvimento-de-sistemas.webp',
        date: '01/06/2019',
        category: 'Graduação',
      },
      {
        id: 12,
        title: 'GitLab CI - Para Pipelines CI/CD & DevOps',
        institution: 'Claudio Antonio da Silva',
        imageUrl: '/certificates/courses/gitlab-ci-pipelines-cicd-devops.webp',
        date: '14/06/2023',
        category: 'Horas',
      },
      {
        id: 13,
        title: 'TypeScript do básico ao avançado (c/ React, Express)',
        institution: 'Matheus Battisti',
        imageUrl: '/certificates/courses/typescript-do-basico-ao-avancado.webp',
        date: '07/06/2023',
        category: 'Horas',
      },
      {
        id: 14,
        title: 'Docker: Ferramenta essencial para Desenvolvedores',
        institution: 'Leonardo Moura Leitao / Cod3r',
        imageUrl: '/certificates/courses/docker-ferramenta-essencial-para-desenvolvedores.webp',
        date: '07/05/2023',
        category: 'Horas',
      },
      {
        id: 2,
        title: 'SOLID - Os 5 Princípios Para as Boas Práticas da POO',
        institution: 'Jorge Sant Ana',
        imageUrl: '/certificates/courses/solid-os-5-principios-para-as-boas-praticas-da-poo.webp',
        date: '25/04/2023',
        category: 'Horas',
      },
      {
        id: 3,
        title: 'Vue JS 3: Desenvolvimento Web Moderno com Vuex & Vue Router',
        institution: 'Ivan Lourenço Gomes',
        imageUrl: '/certificates/courses/css-avançado.webp',
        date: '14/04/2023',
        category: 'Horas',
      },
      {
        id: 4,
        title: 'CSS Avançado - Sass, CSS Grid Layout e CSS Modules',
        institution: 'Brunão Sousa',
        imageUrl: '/certificates/courses/vue-js-3.webp',
        date: '14/04/2023',
        category: 'Horas',
      },
      {
        id: 5,
        title: 'Scrum para Desenvolvedores de Software',
        institution: 'Bruno Coutinho',
        imageUrl: '/certificates/courses/scrum-para-desenvolvedores-de-software.webp',
        date: '05/01/2023',
        category: 'Horas',
      },
      {
        id: 6,
        title: 'Git e Github Essencial para o Desenvolvedor',
        institution: 'Geek University',
        imageUrl: '/certificates/courses/git-e-github-essencial.webp',
        date: '02/01/2023',
        category: 'Horas',
      },
      {
        id: 7,
        title: 'Trilha Especializar',
        institution: 'Rocketseat',
        imageUrl: '/certificates/courses/discover-especializar-certificate.webp',
        date: '14/10/2022',
        category: 'Horas',
      },
      {
        id: 8,
        title: 'Trilha Fundamentar',
        institution: 'Rocketseat',
        imageUrl: '/certificates/courses/discover-fundamentar-certificate.webp',
        date: '02/09/2022',
        category: 'Horas',
      },
      {
        id: 9,
        title: 'Trilha Conectar',
        institution: 'Rocketseat',
        imageUrl: '/certificates/courses/discover-conectar-certificate.webp',
        date: '09/08/2022',
        category: 'Horas',
      },
      {
        id: 10,
        title: 'PHP 7 Completo',
        institution: 'Hode',
        imageUrl: '/certificates/courses/php7-hcode.webp',
        date: '09/06/2022',
        category: 'Horas',
      },
      {
        id: 11,
        title: 'Git e GitHub do básico ao avançado',
        institution: 'Matheus Battisti',
        imageUrl: '/certificates/courses/git-github-avancado.webp',
        date: '24/05/2022',
        category: 'Horas',
      },
  ];